### ISSUE TITLE
我请求官网接口没有110100这个编码，为何你有这个编码？

### ISSUE THREAD

**Issue by shaly** [nine-city/CityMap#2]

**Comment by nine-city** [comment]
之前的API里面，直辖市有这么一个虚拟二级节点。新版已经没有提供了。忽略即可

**Comment by shaly** [comment]
> 之前的API里面，直辖市有这么一个虚拟二级节点。新版已经没有提供了。忽略即可

还有一个疑问：为何你新增语句有四千个？我看了别的一版都是三千五六左右
